import { jsPDF } from "jspdf";

const PRIMARY = [37, 99, 235];
const TEXT = [30, 41, 59];
const MUTED = [100, 116, 139];
const LINE = [203, 213, 225];
const SOFT = [248, 250, 252];
const GREEN = [22, 163, 74];
const ORANGE = [249, 115, 22];
const RED = [220, 38, 38];
const MARGIN = 15;
const PAGE_W = 210;
const PAGE_H = 297;
const CONTENT_W = PAGE_W - MARGIN * 2;

export function downloadSessionReport({ patient, session, t = {} }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const generatedAt = new Date().toLocaleDateString();
  const results = session.results ?? {};
  const recommendations = results.recommendations ?? [];
  const clinicianName = t.clinicianName ?? "Dr. Habiba El Kettani";
  const clinicianRole = t.clinicianRole ?? "Physiotherapist";
  const severity = getSeverity(session.totalScore ?? results.totalBalanceScore, t);

  drawCoverPage(doc, { patient, session, generatedAt, clinicianName, severity, t });
  drawResultsPage(doc, { patient, session, results, t });
  drawInterpretationPage(doc, { patient, session, results, recommendations, t });
  drawTrendAppendixPage(doc, { patient, session, results, t });
  drawSignaturePage(doc, { patient, generatedAt, clinicianName, clinicianRole, t });

  addHeadersAndFooters(doc, patient, generatedAt, t);
  doc.save(`BalanceRehab_${patient.patientCode}_${session.id}.pdf`);
}

function drawCoverPage(doc, { patient, session, generatedAt, clinicianName, severity, t }) {
  doc.setFillColor(...SOFT);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");

  doc.setTextColor(...PRIMARY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(30);
  doc.text("BalanceRehab", MARGIN, 30);

  doc.setTextColor(...TEXT);
  doc.setFontSize(16);
  doc.text(t.pdfReportSubtitle ?? "Balance Assessment Report", MARGIN, 40);

  doc.setDrawColor(...PRIMARY);
  doc.setLineWidth(0.6);
  doc.line(MARGIN, 48, PAGE_W - MARGIN, 48);

  doc.setFillColor(255, 255, 255);
  doc.roundedRect(MARGIN, 60, CONTENT_W, 58, 3, 3, "F");
  doc.setDrawColor(...LINE);
  doc.roundedRect(MARGIN, 60, CONTENT_W, 58, 3, 3, "S");

  const left = [
    [t.pdfPatientName ?? "Patient name", patient.fullName],
    [t.pdfIdCode ?? "ID code", patient.patientCode],
    [t.age ?? "Age", valueOrDash(patient.age)],
    [t.sex ?? "Sex", displaySex(t, patient.sex)],
    [t.pdfHeight ?? "Height", patient.heightCm ? `${patient.heightCm} cm` : "-"],
    [t.pdfWeight ?? "Weight", patient.weightKg ? `${patient.weightKg} kg` : "-"],
  ];
  const right = [
    [t.pdfClinician ?? "Clinician", clinicianName],
    [t.date ?? "Date", session.date ?? generatedAt],
    [t.test ?? "Test type", testTypeLabel(t, session.testType)],
    [t.duration ?? "Duration", `${session.durationSeconds ?? "-"} ${t.seconds ?? "seconds"}`],
    [t.acquisitionMode ?? "Mode", acquisitionModeLabel(t, session)],
  ];

  drawInfoList(doc, left, MARGIN + 8, 72, 76);
  drawInfoList(doc, right, MARGIN + 100, 72, 76);

  doc.setFillColor(255, 255, 255);
  doc.roundedRect(50, 142, 110, 58, 4, 4, "F");
  doc.setDrawColor(...LINE);
  doc.roundedRect(50, 142, 110, 58, 4, 4, "S");

  doc.setTextColor(...TEXT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(48);
  doc.text(`${session.totalScore ?? resultsValue(session, "totalBalanceScore")}/100`, PAGE_W / 2, 166, { align: "center" });

  doc.setTextColor(...severity.color);
  doc.setFontSize(13);
  doc.text(severity.label, PAGE_W / 2, 184, { align: "center" });

  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(template(t.pdfGeneratedFooter ?? "Generated by BalanceRehab | {date} | For clinical support use only", { date: generatedAt }), PAGE_W / 2, 282, { align: "center" });
}

function drawResultsPage(doc, { patient, session, results, t }) {
  doc.addPage();
  let y = 32;
  y = sectionTitle(doc, t.pdfPostureResults ?? "Posture Assessment Results", y);

  const rows = [
    [t.trunkDeviation ?? "Trunk Deviation", `${valueOrDash(results.trunkDeviation)} deg`, "<8 deg", statusSymbol(results.trunkDeviation, 8, false, t)],
    [t.shoulderAsymmetry ?? "Shoulder Asymmetry", `${valueOrDash(results.shoulderAsymmetry)}%`, "<5%", statusSymbol(results.shoulderAsymmetry, 5, false, t)],
    [t.hipAsymmetry ?? "Hip Asymmetry", `${valueOrDash(results.hipAsymmetry)}%`, "<5%", statusSymbol(results.hipAsymmetry, 5, false, t)],
    [t.bodyCenterDeviation ?? "Body Center Deviation", `${valueOrDash(results.bodyCenterDeviation)}%`, "<9%", statusSymbol(results.bodyCenterDeviation, 9, false, t)],
    [t.postureStability ?? "Posture Stability Score", `${valueOrDash(session.postureScore ?? results.postureStabilityScore)}/100`, ">75", statusSymbol(session.postureScore ?? results.postureStabilityScore, 75, true, t)],
  ];
  y = drawTable(doc, {
    y,
    columns: [t.metric ?? "Metric", t.pdfValue ?? "Value", t.pdfReference ?? "Reference", t.status ?? "Status"],
    widths: [72, 38, 38, 32],
    rows,
  });

  y += 12;
  y = sectionTitle(doc, t.pdfFullBodyIndicators ?? "Full-Body Movement Indicators", y);
  y = drawTable(doc, {
    y,
    columns: [t.metric ?? "Metric", t.pdfValue ?? "Value", t.pdfReference ?? "Reference", t.status ?? "Status"],
    widths: [72, 38, 38, 32],
    rows: [
      [t.alignmentScore ?? "Alignment Score", `${valueOrDash(results.alignmentScore)}/100`, ">75", statusSymbol(results.alignmentScore, 75, true, t)],
      [t.symmetryScore ?? "Symmetry Score", `${valueOrDash(results.symmetryScore)}/100`, ">75", statusSymbol(results.symmetryScore, 75, true, t)],
      [t.trunkControl ?? "Trunk Control", `${valueOrDash(results.trunkControlScore)}/100`, ">75", statusSymbol(results.trunkControlScore, 75, true, t)],
      [t.posturalControl ?? "Postural Control", `${valueOrDash(results.posturalControlScore)}/100`, ">75", statusSymbol(results.posturalControlScore, 75, true, t)],
      [t.pelvicTilt ?? "Pelvic Tilt", `${valueOrDash(results.pelvicTilt)} deg`, "<5 deg", statusSymbol(results.pelvicTilt, 5, false, t)],
      [t.headTilt ?? "Head Tilt", `${valueOrDash(results.headTilt)} deg`, "<8 deg", statusSymbol(results.headTilt, 8, false, t)],
      [t.armSymmetry ?? "Arm Symmetry", `${valueOrDash(results.armSymmetry)}%`, "<12%", statusSymbol(results.armSymmetry, 12, false, t)],
      [t.weightShift ?? "Weight Shift", `${valueOrDash(results.weightShiftEstimation)}%`, "<9%", statusSymbol(results.weightShiftEstimation, 9, false, t)],
    ],
  });

  y += 12;
  y = sectionTitle(doc, t.pdfTrackingCoverage ?? "Tracking Coverage", y);
  y = drawTable(doc, {
    y,
    columns: [t.trackingSource ?? "Tracking source", t.pdfDetectedFrames ?? "Detected frames", t.status ?? "Status"],
    widths: [72, 54, 54],
    rows: trackingCoverageRows(results.engineCoverage, t),
  });

  if (y > 205) {
    doc.addPage();
    y = 32;
  }

  if (results.availableMetrics?.board) {
    y += 12;
    y = sectionTitle(doc, t.swayMetrics ?? "Sway Metrics", y);
    y = drawTable(doc, {
      y,
      columns: [t.pdfApSwayMean ?? "AP Sway Mean", t.pdfMlSwayMean ?? "ML Sway Mean", t.pdfApSwayMax ?? "AP Sway Max", t.pdfMlSwayMax ?? "ML Sway Max", t.swayVelocity ?? "Sway Velocity"],
      widths: [36, 36, 36, 36, 36],
      rows: [[
        `${valueOrDash(results.meanSwayAp)} mm`,
        `${valueOrDash(results.meanSwayMl)} mm`,
        `${valueOrDash(results.maxSwayAp)} mm`,
        `${valueOrDash(results.maxSwayMl)} mm`,
        `${valueOrDash(results.swayVelocity)} mm/s`,
      ]],
    });
  } else {
    y += 12;
    doc.setFillColor(255, 247, 237);
    doc.roundedRect(MARGIN, y, CONTENT_W, 22, 3, 3, "F");
    doc.setTextColor(...ORANGE);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(t.pdfBoardUnavailable ?? "Board sway metrics are not available in webcam-only mode.", MARGIN + 5, y + 13);
    y += 26;
  }

  drawScoreBand(doc, patient, session, Math.min(Math.max(y + 8, 212), 238), t);
}

function drawInterpretationPage(doc, { session, results, recommendations, t }) {
  doc.addPage();
  let y = 32;
  y = sectionTitle(doc, t.clinicalImpression ?? "Clinical Impression", y);
  y = drawTextBlock(doc, session.clinician_impression ?? session.interpretation ?? results.interpretation ?? "-", y);

  y += 8;
  y = sectionTitle(doc, t.recommendations ?? "Rehabilitation Recommendations", y);
  recommendations.forEach((item, index) => {
    y = drawWrappedLine(doc, `${index + 1}. ${item}`, MARGIN + 4, y, CONTENT_W - 8);
  });

  y += 8;
  y = sectionTitle(doc, t.testConditions ?? "Assessment Conditions", y);
  drawTable(doc, {
    y,
    columns: [t.conditions ?? "Condition", t.pdfValue ?? "Value"],
    widths: [60, 120],
    rows: [
      [t.test ?? "Test type", testTypeLabel(t, session.testType)],
      [t.visionCondition ?? "Visual condition", conditionLabel(t, session.condition)],
      [t.duration ?? "Duration", `${session.durationSeconds ?? "-"} ${t.seconds ?? "seconds"}`],
      [t.acquisitionMode ?? "Acquisition mode", acquisitionModeLabel(t, session)],
      [t.supportRing ?? "Support ring", session.supportRing ?? "-"],
    ],
  });
}

function drawTrendAppendixPage(doc, { results, t }) {
  doc.addPage();
  let y = 32;
  y = sectionTitle(doc, t.pdfTrendSummary ?? "Assessment Trend Summary", y);

  const samples = results.samples ?? [];
  if (!samples.length) {
    drawTextBlock(doc, t.pdfNoSamples ?? "Time-series posture samples were not recorded for this session.", y);
    return;
  }

  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(t.pdfSamplesCaptured ?? "Posture stability samples captured during the assessment.", MARGIN, y);
  y += 12;

  drawMiniLineChart(doc, samples, {
    x: MARGIN,
    y,
    width: CONTENT_W,
    height: 72,
    key: "posture",
    min: 0,
    max: 100,
    color: PRIMARY,
    label: t.pdfPostureOverTime ?? "Posture Stability Over Time",
  });

  if (results.availableMetrics?.board) {
    drawSwayScatter(doc, samples, MARGIN, y + 94, CONTENT_W, 72, t);
  } else {
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(...LINE);
    doc.roundedRect(MARGIN, y + 94, CONTENT_W, 34, 3, 3, "FD");
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(t.swayPathAvailableBoard ?? "Sway path available with ESP32 balance board.", MARGIN + 5, y + 114);
  }
}

function drawSignaturePage(doc, { generatedAt, clinicianName, clinicianRole, t }) {
  doc.addPage();
  let y = 34;
  y = sectionTitle(doc, t.pdfDisclaimerSignature ?? "Disclaimer & Signature", y);

  doc.setFillColor(...SOFT);
  doc.roundedRect(MARGIN, y, CONTENT_W, 48, 3, 3, "F");
  doc.setTextColor(...TEXT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(clinicianName, MARGIN + 6, y + 14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...MUTED);
  doc.text(clinicianRole, MARGIN + 6, y + 22);
  doc.text(`${t.pdfReportDate ?? "Report date"}: ${generatedAt}`, MARGIN + 6, y + 32);
  y += 70;

  doc.setDrawColor(...TEXT);
  doc.line(MARGIN, y, MARGIN + 80, y);
  doc.line(MARGIN + 110, y, PAGE_W - MARGIN, y);
  doc.setTextColor(...MUTED);
  doc.setFontSize(9);
  doc.text(t.pdfSignature ?? "Signature", MARGIN, y + 7);
  doc.text(t.date ?? "Date", MARGIN + 110, y + 7);

  y += 28;
  y = sectionTitle(doc, t.pdfClinicalSupportNotice ?? "Clinical Support Notice", y);
  drawTextBlock(
    doc,
    t.pdfLegalNotice ?? "This report is generated as a clinical support tool and does not replace professional medical judgment or certified diagnosis.",
    y,
  );
}

function addHeadersAndFooters(doc, patient, generatedAt, t) {
  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    if (page > 1) {
      doc.setFillColor(255, 255, 255);
      doc.rect(0, 0, PAGE_W, 18, "F");
      doc.setTextColor(...PRIMARY);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text("BalanceRehab", MARGIN, 12);
      doc.setTextColor(...MUTED);
      doc.setFont("helvetica", "normal");
      doc.text(`${patient.fullName} | ${patient.patientCode}`, PAGE_W - MARGIN, 12, { align: "right" });
      doc.setDrawColor(...LINE);
      doc.line(MARGIN, 18, PAGE_W - MARGIN, 18);
    }

    doc.setDrawColor(...LINE);
    doc.line(MARGIN, 278, PAGE_W - MARGIN, 278);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(template(t.pdfGeneratedFooter ?? "Generated by BalanceRehab | {date} | For clinical support use only", { date: generatedAt }), MARGIN, 285);
    doc.text(template(t.pdfPageCount ?? "Page {page} of {pages}", { page, pages }), PAGE_W - MARGIN, 285, { align: "right" });
  }
}

function sectionTitle(doc, title, y) {
  doc.setFillColor(...PRIMARY);
  doc.rect(MARGIN, y - 7, 4, 9, "F");
  doc.setTextColor(...TEXT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(title, MARGIN + 7, y);
  return y + 12;
}

function drawInfoList(doc, rows, x, y, width) {
  rows.forEach(([label, value], index) => {
    const lineY = y + index * 7;
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`${label}:`, x, lineY);
    doc.setTextColor(...TEXT);
    doc.setFont("helvetica", "bold");
    doc.text(String(valueOrDash(value)), x + 32, lineY, { maxWidth: width - 32 });
  });
}

function drawTable(doc, { y, columns, widths, rows }) {
  const rowH = 10;
  let currentY = y;
  let x = MARGIN;

  doc.setFillColor(226, 232, 240);
  doc.rect(MARGIN, currentY, CONTENT_W, rowH, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...TEXT);
  columns.forEach((column, index) => {
    doc.text(column, x + 3, currentY + 6.5, { maxWidth: widths[index] - 5 });
    x += widths[index];
  });
  currentY += rowH;

  rows.forEach((row, rowIndex) => {
    x = MARGIN;
    doc.setFillColor(rowIndex % 2 === 0 ? 255 : 248, rowIndex % 2 === 0 ? 255 : 250, rowIndex % 2 === 0 ? 255 : 252);
    doc.rect(MARGIN, currentY, CONTENT_W, rowH, "F");
    doc.setDrawColor(...LINE);
    doc.line(MARGIN, currentY + rowH, PAGE_W - MARGIN, currentY + rowH);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...TEXT);
    row.forEach((cell, index) => {
      const isOk = cell === "OK";
      const isStatusCell = index === row.length - 1 && (isOk || cell === "Review" || cell === "A revoir");
      if (isStatusCell) doc.setTextColor(isOk ? GREEN[0] : ORANGE[0], isOk ? GREEN[1] : ORANGE[1], isOk ? GREEN[2] : ORANGE[2]);
      doc.text(String(valueOrDash(cell)), x + 3, currentY + 6.5, { maxWidth: widths[index] - 5 });
      if (isStatusCell) doc.setTextColor(...TEXT);
      x += widths[index];
    });
    currentY += rowH;
  });

  doc.setDrawColor(...LINE);
  doc.rect(MARGIN, y, CONTENT_W, rowH * (rows.length + 1), "S");
  return currentY;
}

function drawTextBlock(doc, text, y) {
  doc.setFillColor(...SOFT);
  doc.roundedRect(MARGIN, y, CONTENT_W, 46, 3, 3, "F");
  return drawWrappedLine(doc, text, MARGIN + 5, y + 10, CONTENT_W - 10) + 8;
}

function drawWrappedLine(doc, text, x, y, maxWidth) {
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...TEXT);
  doc.setFontSize(10);
  const lines = doc.splitTextToSize(String(text ?? "-"), maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * 5.5 + 2;
}

function drawScoreBand(doc, patient, session, y, t) {
  const severity = getSeverity(session.totalScore, t);
  doc.setFillColor(...severity.bg);
  doc.roundedRect(MARGIN, y, CONTENT_W, 34, 3, 3, "F");
  doc.setTextColor(...severity.color);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(`${session.totalScore}/100`, MARGIN + 8, y + 19);
  doc.setFontSize(11);
  doc.text(severity.label, MARGIN + 46, y + 18);
  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`${patient.fullName} | ${testTypeLabel(t, session.testType)} | ${conditionLabel(t, session.condition)}`, MARGIN + 46, y + 27);
}

function drawMiniLineChart(doc, samples, { x, y, width, height, key, min, max, color, label }) {
  doc.setTextColor(...TEXT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(label, x, y - 4);
  doc.setDrawColor(...LINE);
  doc.rect(x, y, width, height, "S");
  doc.setDrawColor(226, 232, 240);
  for (let i = 1; i < 4; i += 1) doc.line(x, y + (height / 4) * i, x + width, y + (height / 4) * i);

  doc.setDrawColor(...color);
  doc.setLineWidth(0.6);
  samples.forEach((sample, index) => {
    if (index === 0) return;
    const prev = samples[index - 1];
    const x1 = x + ((index - 1) / (samples.length - 1)) * width;
    const x2 = x + (index / (samples.length - 1)) * width;
    const y1 = y + height - ((Number(prev[key]) - min) / (max - min)) * height;
    const y2 = y + height - ((Number(sample[key]) - min) / (max - min)) * height;
    doc.line(x1, y1, x2, y2);
  });
  doc.setLineWidth(0.2);
}

function drawSwayScatter(doc, samples, x, y, width, height, t) {
  doc.setTextColor(...TEXT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(t.estimatedMovementPath ?? "Estimated movement path", x, y - 4);
  doc.setDrawColor(...LINE);
  doc.rect(x, y, width, height, "S");
  doc.setDrawColor(...ORANGE);
  doc.line(x + width / 2, y, x + width / 2, y + height);
  doc.line(x, y + height / 2, x + width, y + height / 2);
  doc.setFillColor(...PRIMARY);
  samples
    .filter((sample) => sample.ap != null && sample.ml != null)
    .forEach((sample) => {
      const px = x + width / 2 + Number(sample.ml);
      const py = y + height / 2 - Number(sample.ap);
      doc.circle(Math.max(x + 2, Math.min(x + width - 2, px)), Math.max(y + 2, Math.min(y + height - 2, py)), 0.8, "F");
    });
}

function getSeverity(score = 0, t = {}) {
  if (score >= 80) return { label: (t.stableResult ?? "Stable").toUpperCase(), color: GREEN, bg: [240, 253, 244] };
  if (score >= 65) return { label: (t.moderateInstability ?? "Moderate instability").toUpperCase(), color: ORANGE, bg: [255, 247, 237] };
  return { label: (t.highInstability ?? "High instability").toUpperCase(), color: RED, bg: [254, 242, 242] };
}

function statusSymbol(value, threshold, higherIsBetter, t = {}) {
  const numeric = Number(value);
  if (Number.isNaN(numeric)) return t.pdfReview ?? "Review";
  return higherIsBetter
    ? (numeric > threshold ? (t.pdfOk ?? "OK") : (t.pdfReview ?? "Review"))
    : (numeric < threshold ? (t.pdfOk ?? "OK") : (t.pdfReview ?? "Review"));
}

function trackingCoverageRows(engineCoverage = {}, t = {}) {
  return [
    trackingCoverageRow(t.poseTracking ?? "Pose tracking", engineCoverage.pose, t),
    trackingCoverageRow(t.faceTracking ?? "Face tracking", engineCoverage.face, t),
    trackingCoverageRow(t.handTracking ?? "Hand tracking", engineCoverage.hands, t),
  ];
}

function trackingCoverageRow(label, coverage = {}, t = {}) {
  if (!coverage?.available) {
    return [label, "-", t.notAvailable ?? "Not available"];
  }
  const percent = Number(coverage.detectedPercent) || 0;
  const status = percent >= 75 ? (t.pdfOk ?? "OK") : percent >= 35 ? (t.pdfReview ?? "Review") : (t.attention ?? "Attention");
  return [label, `${percent}%`, status];
}

function displaySex(t, sex) {
  if (sex === "F" || sex === "Female") return t.female ?? "Female";
  if (sex === "M" || sex === "Male") return t.male ?? "Male";
  return sex ?? "-";
}

function resultsValue(session, key) {
  return session.results?.[key] ?? "-";
}

function valueOrDash(value) {
  return value == null || value === "" ? "-" : value;
}

function testTypeLabel(t, testType) {
  const normalized = String(testType ?? "").toLowerCase();
  if (normalized === "static") return t.staticTest ?? "Static test";
  if (normalized === "dynamic") return t.dynamicTest ?? "Dynamic test";
  return testType ?? "-";
}

function conditionLabel(t, condition) {
  const normalized = String(condition ?? "").toLowerCase().replace("_", " ");
  if (normalized === "eyes open") return t.eyesOpen ?? "Eyes open";
  if (normalized === "eyes closed") return t.eyesClosed ?? "Eyes closed";
  return condition ?? "-";
}

function acquisitionModeLabel(t, session) {
  const normalized = String(session.acquisitionModeKey ?? session.acquisitionMode ?? "").toLowerCase();
  if (normalized.includes("webcam")) return t.webcamBasedAssessment ?? "Webcam-Based Assessment";
  if (normalized.includes("demo")) return t.demoAssessmentMode ?? "Demo Mode";
  if (normalized.includes("combined")) return t.combinedAssessmentMode ?? "Webcam + ESP32";
  if (normalized.includes("board")) return t.boardAssessmentMode ?? "ESP32 Only";
  return session.acquisitionMode ?? "-";
}

function template(text = "", values = {}) {
  return Object.entries(values).reduce((current, [key, value]) => current.replaceAll(`{${key}}`, value ?? ""), text);
}
